# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7aa8b0990f8597e6ac428841243135b1d8ea91e92030efdbd8546de7f4f22ade436f187a62bbec1cd9ec2a968b63116f7bd0b70cc153589825fc07dc64f97050

test:
  secret_key_base: 2ba2638eaf39f2bd682055720d282e9b9a17600344f121d8eeb9c36fe07bd7d4953f444d05f766706cc6dcabcdb8bdf44474fa52e3fbcb4b814aea792bda9b83

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
